# Generated by Django 5.2.2 on 2025-11-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchlist_app", "0005_review_user_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="avg_rating",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="watchlist",
            name="number_of_ratings",
            field=models.IntegerField(default=0),
        ),
    ]
